import type { AppConfig } from './types'

function targetSummary(config: AppConfig): string[] {
  const lines: string[] = []
  const win = config.targets.windows
  const lin = config.targets.linux
  const mac = config.targets.mac
  if (win.includes('nsis')) lines.push('- Windows — NSIS installer (`Setup.exe`)')
  if (win.includes('portable')) lines.push('- Windows — Portable executable')
  if (lin.includes('appimage')) lines.push('- Linux — AppImage')
  if (lin.includes('deb')) lines.push('- Linux — Debian package (`.deb`)')
  if (lin.includes('rpm')) lines.push('- Linux — RPM package (`.rpm`)')
  if (mac.includes('dmg')) lines.push('- macOS — DMG disk image')
  if (mac.includes('zip')) lines.push('- macOS — Zipped `.app` bundle')
  return lines
}

export function readmeMd(config: AppConfig): string {
  const hasWin = config.targets.windows.length > 0
  const hasLinux = config.targets.linux.length > 0
  const hasMac = config.targets.mac.length > 0

  return `# ${config.name}

**Version:** ${config.version}  
**Publisher:** ${config.publisher}  
**App ID:** \`${config.appId}\`  
${config.description ? `\n${config.description}\n` : ''}
This is a self-contained desktop application project generated by **HTML → App Builder**.
It wraps your HTML project in [Electron](https://www.electronjs.org/) and uses
[electron-builder](https://www.electron.build/) to produce native apps and installers.

## Quick start (zero configuration)

1. Extract this ZIP.
2. Open the extracted folder.
${hasWin ? '3. **Windows:** double-click `build.bat`.\n' : ''}${
    hasLinux || hasMac
      ? `${hasWin ? '4' : '3'}. **Linux / macOS:** open a terminal in this folder and run \`chmod +x build.sh && ./build.sh\`.\n`
      : ''
  }
The script checks for Node.js, installs dependencies automatically, builds your
app, and opens the \`dist/\` output folder.

## Requirements

- [Node.js](https://nodejs.org/) 18 or newer (includes npm).
- Internet access on the first build (to download Electron & build tools).
${hasWin ? '- Windows builds run on Windows.\n' : ''}${hasLinux ? '- Linux packages (`.deb` / `.rpm`) build best on Linux.\n' : ''}${hasMac ? '- **macOS builds must be produced on macOS** and, for distribution, code-signed & notarized by Apple.\n' : ''}

## Selected build targets

${targetSummary(config).join('\n')}

## Manual build

From this folder:

\`\`\`bash
npm install
${hasWin ? 'npm run dist:win     # Windows targets\n' : ''}${hasLinux ? 'npm run dist:linux   # Linux targets\n' : ''}${hasMac ? 'npm run dist:mac     # macOS targets\n' : ''}npm run dist         # everything for the current OS
\`\`\`

Run the app without packaging:

\`\`\`bash
npm install
npm start
\`\`\`

## Output

Finished apps and installers are written to the **\`dist/\`** folder.

## Project layout

\`\`\`
${config.name}/
├── app/                 your HTML project (entry: ${config.entry})
├── config/
│   └── app-config.json  runtime window & app settings
├── icons/
│   └── icon.png         application icon
├── scripts/             per-platform build scripts
├── main.js              Electron main process
├── preload.js           secure preload bridge
├── package.json         dependencies + electron-builder config
├── build.bat / build.sh one-click builders
├── README.md
└── BUILD.md             detailed build instructions
\`\`\`

## Troubleshooting

- **"Node.js was not found"** — install Node.js from https://nodejs.org, reopen the terminal, and retry.
- **First build is slow** — Electron and the build tools are downloaded once and cached.
- **Windows SmartScreen warning** — unsigned apps show a warning; click *More info → Run anyway*, or sign the app with a code-signing certificate.
- **macOS "app is damaged / unidentified developer"** — the app is unsigned; sign & notarize it, or right-click → Open on your own machine.
- **Missing assets in the app** — make sure every file referenced by your HTML was included in the upload; check the warnings shown in the builder.

---

Generated with HTML → App Builder.
`
}

export function buildMd(config: AppConfig): string {
  const hasWin = config.targets.windows.length > 0
  const hasLinux = config.targets.linux.length > 0
  const hasMac = config.targets.mac.length > 0

  const sections: string[] = []

  sections.push(`# Build instructions — ${config.name}

This document explains, step by step, how to turn this project into native
applications and installers on each platform.

## Prerequisites (all platforms)

- Install [Node.js](https://nodejs.org/) 18+ (includes npm).
- Keep an internet connection available for the first build.
`)

  if (hasWin) {
    sections.push(`## Windows

1. Extract the ZIP.
2. Open the extracted folder.
3. Double-click **\`build.bat\`** (or run \`scripts\\build-windows.bat\`).
4. Wait for the build to finish — dependencies install automatically.
5. Open the **\`dist\\\`** folder.
6. Run the produced installer or portable executable.

${
  config.targets.windows.includes('portable')
    ? 'For only the portable build, run `scripts\\build-portable.bat`.\n'
    : ''
}`)
  }

  if (hasLinux) {
    sections.push(`## Linux

1. Open a terminal in the extracted folder.
2. Make the script executable: \`chmod +x build.sh scripts/build-linux.sh\`
3. Run \`./scripts/build-linux.sh\` (or \`./build.sh\`).
4. Find the output (\`.AppImage\`, \`.deb\`, \`.rpm\`) in **\`dist/\`**.

> Building \`.deb\`/\`.rpm\` works most reliably on a Linux host. AppImage runs on
> most distributions without installation.
`)
  }

  if (hasMac) {
    sections.push(`## macOS

1. Open a terminal in the extracted folder.
2. Make the script executable: \`chmod +x build.sh scripts/build-macos.sh\`
3. Run \`./scripts/build-macos.sh\` (or \`./build.sh\`).
4. Find the \`.dmg\` / \`.app\` in **\`dist/\`**.

> macOS applications **must be built on macOS**. For distribution outside your
> own machine you must code-sign and notarize the app with an Apple Developer ID.
`)
  }

  sections.push(`## What the build produces

The \`electron-builder\` configuration in \`package.json\` defines the targets you
selected. Change the \`build\` section there to add or remove targets later
without regenerating the project.

## Cleaning

Delete the \`dist/\` and \`node_modules/\` folders to reset. The next build will
reinstall dependencies automatically.
`)

  return sections.join('\n')
}
