import type { AppConfig } from './types'

const ELECTRON_VERSION = '^33.2.1'
const ELECTRON_BUILDER_VERSION = '^25.1.8'

/** main.js — the Electron main process that hosts the packaged HTML app. */
export function mainJs(): string {
  return `const { app, BrowserWindow, Menu, shell } = require('electron')
const path = require('path')
const fs = require('fs')

// Load the build configuration generated by HTML -> App Builder.
const config = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'config', 'app-config.json'), 'utf-8')
)

let mainWindow = null

function createWindow() {
  const win = new BrowserWindow({
    width: config.window.width,
    height: config.window.height,
    minWidth: config.window.minWidth || undefined,
    minHeight: config.window.minHeight || undefined,
    resizable: config.window.resizable !== false,
    fullscreen: !!config.window.fullscreen,
    frame: config.window.frameless ? false : true,
    title: config.name,
    icon: path.join(__dirname, 'icons', 'icon.png'),
    show: false,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
    },
  })

  // Hide the default application menu for a cleaner app-like feel.
  Menu.setApplicationMenu(null)

  win.loadFile(path.join(__dirname, 'app', config.entry))

  win.once('ready-to-show', () => {
    if (config.window.maximized) win.maximize()
    win.show()
  })

  // Open external links (http/https/mailto) in the user's browser instead
  // of inside the app window.
  win.webContents.setWindowOpenHandler(({ url }) => {
    if (/^https?:|^mailto:/i.test(url)) {
      shell.openExternal(url)
      return { action: 'deny' }
    }
    return { action: 'allow' }
  })

  mainWindow = win
}

app.whenReady().then(() => {
  createWindow()
  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit()
})
`
}

/** preload.js — minimal, secure preload bridge. */
export function preloadJs(): string {
  return `// Preload script. Runs before the packaged HTML page in an isolated context.
// Extend this file if you need to expose safe native capabilities to your page
// via contextBridge. By default nothing extra is exposed.
const { contextBridge } = require('electron')

contextBridge.exposeInMainWorld('appInfo', {
  platform: process.platform,
  versions: process.versions,
})
`
}

/** package.json including the electron-builder "build" block. */
export function packageJson(config: AppConfig, opts: { slug: string }): string {
  const build: Record<string, unknown> = {
    appId: config.appId,
    productName: config.name,
    copyright: `Copyright © ${new Date().getFullYear()} ${config.publisher}`,
    directories: { output: 'dist', buildResources: 'build' },
    files: ['main.js', 'preload.js', 'config/**/*', 'app/**/*', 'icons/**/*'],
  }

  if (config.targets.windows.length > 0) {
    build.win = {
      target: config.targets.windows.map((t) =>
        t === 'nsis' ? 'nsis' : 'portable',
      ),
      icon: 'icons/icon.png',
      artifactName: '${productName}-${version}-${arch}.${ext}',
    }
    if (config.targets.windows.includes('nsis')) {
      const nsis: Record<string, unknown> = {
        oneClick: config.installer.oneClick,
        perMachine: config.installer.perMachine,
        allowElevation: true,
        allowToChangeInstallationDirectory:
          !config.installer.oneClick && config.installer.allowDirectorySelection,
        createDesktopShortcut: config.installer.desktopShortcut,
        createStartMenuShortcut: config.installer.startMenuShortcut,
        shortcutName: config.name,
      }
      if (config.installer.license.trim()) nsis.license = 'LICENSE.txt'
      build.nsis = nsis
    }
    if (config.targets.windows.includes('portable')) {
      build.portable = { artifactName: '${productName}-${version}-portable.exe' }
    }
  }

  if (config.targets.linux.length > 0) {
    build.linux = {
      target: config.targets.linux.map((t) =>
        t === 'appimage' ? 'AppImage' : t,
      ),
      icon: 'icons/icon.png',
      category: 'Utility',
      maintainer: config.publisher,
      synopsis: config.description || config.name,
    }
  }

  if (config.targets.mac.length > 0) {
    build.mac = {
      target: config.targets.mac.map((t) => (t === 'zip' ? 'zip' : 'dmg')),
      icon: 'icons/icon.png',
      category: 'public.app-category.utilities',
    }
  }

  const pkg = {
    name: opts.slug,
    version: config.version,
    description: config.description || config.name,
    author: config.publisher,
    main: 'main.js',
    private: true,
    scripts: {
      start: 'electron .',
      dist: 'electron-builder',
      'dist:win': 'electron-builder --win',
      'dist:linux': 'electron-builder --linux',
      'dist:mac': 'electron-builder --mac',
    },
    devDependencies: {
      electron: ELECTRON_VERSION,
      'electron-builder': ELECTRON_BUILDER_VERSION,
    },
    build,
  }

  return JSON.stringify(pkg, null, 2) + '\n'
}

/** app-config.json consumed by main.js at runtime. */
export function appConfigJson(config: AppConfig): string {
  const out = {
    name: config.name,
    version: config.version,
    publisher: config.publisher,
    appId: config.appId,
    description: config.description,
    entry: config.entry,
    window: {
      width: config.window.width,
      height: config.window.height,
      minWidth: config.window.minWidth || undefined,
      minHeight: config.window.minHeight || undefined,
      resizable: config.window.resizable,
      fullscreen: config.window.fullscreen,
      maximized: config.window.maximized,
      frameless: config.window.frameless,
    },
    installer: {
      oneClick: config.installer.oneClick,
      perMachine: config.installer.perMachine,
      allowDirectorySelection: config.installer.allowDirectorySelection,
      desktopShortcut: config.installer.desktopShortcut,
      startMenuShortcut: config.installer.startMenuShortcut,
    },
  }
  return JSON.stringify(out, null, 2) + '\n'
}

/* -------------------------------------------------------------------------- */
/* Build scripts                                                              */
/* -------------------------------------------------------------------------- */

const CRLF = '\r\n'

function batLines(lines: string[]): string {
  return lines.join(CRLF) + CRLF
}

/** Top-level double-click Windows builder with dependency checks. */
export function buildBat(config: AppConfig): string {
  return batLines([
    '@echo off',
    `title ${config.name} Builder`,
    'cd /d "%~dp0"',
    'echo ========================================',
    `echo   ${config.name} Builder`,
    'echo ========================================',
    'echo.',
    'echo Checking requirements...',
    'where node >nul 2>nul',
    'if %errorlevel% neq 0 (',
    '  echo.',
    '  echo Node.js was not found.',
    '  echo Please install Node.js from https://nodejs.org and run this script again.',
    '  echo.',
    '  pause',
    '  exit /b 1',
    ')',
    "for /f \"tokens=*\" %%v in ('node -v') do set NODEV=%%v",
    'echo Node.js: OK %NODEV%',
    'echo.',
    'if not exist node_modules (',
    '  echo Dependencies: installing ^(this can take a few minutes^)...',
    '  call npm install',
    '  if %errorlevel% neq 0 (',
    '    echo.',
    '    echo Dependency installation failed.',
    '    pause',
    '    exit /b 1',
    '  )',
    ') else (',
    '  echo Dependencies: OK',
    ')',
    'echo.',
    'echo Building application...',
    'call npm run dist:win',
    'if %errorlevel% neq 0 (',
    '  echo.',
    '  echo Build failed. See the messages above.',
    '  pause',
    '  exit /b 1',
    ')',
    'echo.',
    'echo Build completed successfully.',
    'echo Output: dist\\',
    'start "" "dist"',
    'echo.',
    'echo Press any key to continue...',
    'pause >nul',
  ])
}

export function buildWindowsBat(config: AppConfig): string {
  return batLines([
    '@echo off',
    `title ${config.name} - Windows build`,
    'cd /d "%~dp0\\.."',
    'where node >nul 2>nul || (echo Node.js not found. Install from https://nodejs.org && pause && exit /b 1)',
    'if not exist node_modules ( call npm install || (pause & exit /b 1) )',
    'call npm run dist:win',
    'if %errorlevel% neq 0 ( echo Build failed. & pause & exit /b 1 )',
    'echo Done. Output in dist\\',
    'pause',
  ])
}

export function buildPortableBat(config: AppConfig): string {
  return batLines([
    '@echo off',
    `title ${config.name} - Portable build`,
    'cd /d "%~dp0\\.."',
    'where node >nul 2>nul || (echo Node.js not found. Install from https://nodejs.org && pause && exit /b 1)',
    'if not exist node_modules ( call npm install || (pause & exit /b 1) )',
    'call npx electron-builder --win portable',
    'if %errorlevel% neq 0 ( echo Build failed. & pause & exit /b 1 )',
    'echo Done. Output in dist\\',
    'pause',
  ])
}

function shLines(lines: string[]): string {
  return lines.join('\n') + '\n'
}

export function buildSh(config: AppConfig): string {
  return shLines([
    '#!/usr/bin/env bash',
    'set -e',
    'cd "$(dirname "$0")"',
    'echo "========================================"',
    `echo "  ${config.name} Builder"`,
    'echo "========================================"',
    'echo',
    'echo "Checking requirements..."',
    'if ! command -v node >/dev/null 2>&1; then',
    '  echo "Node.js was not found. Please install Node.js from https://nodejs.org and run again."',
    '  exit 1',
    'fi',
    'echo "Node.js: OK $(node -v)"',
    'if [ ! -d node_modules ]; then',
    '  echo "Installing dependencies (this can take a few minutes)..."',
    '  npm install',
    'else',
    '  echo "Dependencies: OK"',
    'fi',
    'echo "Building application..."',
    'OS="$(uname -s)"',
    'if [ "$OS" = "Darwin" ]; then',
    '  npm run dist:mac',
    'else',
    '  npm run dist:linux',
    'fi',
    'echo "Build completed. Output: dist/"',
  ])
}

export function buildLinuxSh(config: AppConfig): string {
  return shLines([
    '#!/usr/bin/env bash',
    'set -e',
    'cd "$(dirname "$0")/.."',
    'command -v node >/dev/null 2>&1 || { echo "Node.js not found. Install from https://nodejs.org"; exit 1; }',
    '[ -d node_modules ] || npm install',
    'npm run dist:linux',
    'echo "Done. Output in dist/"',
  ])
}

export function buildMacosSh(config: AppConfig): string {
  return shLines([
    '#!/usr/bin/env bash',
    'set -e',
    'cd "$(dirname "$0")/.."',
    'command -v node >/dev/null 2>&1 || { echo "Node.js not found. Install from https://nodejs.org"; exit 1; }',
    '[ -d node_modules ] || npm install',
    'npm run dist:mac',
    'echo "Done. Output in dist/"',
    'echo "Note: macOS builds must be produced (and ideally code-signed) on macOS."',
  ])
}

export function gitignore(): string {
  return ['node_modules/', 'dist/', '*.log', '.DS_Store'].join('\n') + '\n'
}
